/** @format */

export const SFMC_MEDIA_TYPES: any = {
  ai: { id: 16 },
  psd: { id: 17 },
  pdd: { id: 18 },
  eps: { id: 19 },
  gif: { id: 20 },
  jpe: { id: 21 },
  jpeg: { id: 22 },
  jpg: { id: 23 },
  jp2: { id: 24 },
  jpx: { id: 25 },
  pict: { id: 26 },
  pct: { id: 27 },
  png: { id: 28 },
  tif: { id: 29 },
  tiff: { id: 30 },
  tga: { id: 31 },
  bmp: { id: 32 },
  wmf: { id: 33 },
  vsd: { id: 34 },
  pnm: { id: 35 },
  pgm: { id: 36 },
  pbm: { id: 37 },
  ppm: { id: 38 },
  svg: { id: 39 },
  "3fr": { id: 40 },
  ari: { id: 41 },
  arw: { id: 42 },
  bay: { id: 43 },
  cap: { id: 44 },
  crw: { id: 45 },
  cr2: { id: 46 },
  dcr: { id: 47 },
  dcs: { id: 48 },
  dng: { id: 49 },
  drf: { id: 50 },
  eip: { id: 51 },
  erf: { id: 52 },
  fff: { id: 53 },
  iiq: { id: 54 },
  k25: { id: 55 },
  kdc: { id: 56 },
  mef: { id: 57 },
  mos: { id: 58 },
  mrw: { id: 59 },
  nef: { id: 60 },
  nrw: { id: 61 },
  orf: { id: 62 },
  pef: { id: 63 },
  ptx: { id: 64 },
  pxn: { id: 65 },
  raf: { id: 66 },
  raw: { id: 67 },
  rw2: { id: 68 },
  rwl: { id: 69 },
  rwz: { id: 70 },
  srf: { id: 71 },
  sr2: { id: 72 },
  srw: { id: 73 },
  x3f: { id: 74 },
  "3gp": { id: 75 },
  "3gpp": { id: 76 },
  "3g2": { id: 77 },
  "3gp2": { id: 78 },
  asf: { id: 79 },
  avi: { id: 80 },
  m2ts: { id: 81 },
  mts: { id: 82 },
  dif: { id: 83 },
  dv: { id: 84 },
  mkv: { id: 85 },
  mpg: { id: 86 },
  f4v: { id: 87 },
  flv: { id: 88 },
  mjpg: { id: 89 },
  mjpeg: { id: 90 },
  mxf: { id: 91 },
  mpeg: { id: 92 },
  mp4: { id: 93 },
  m4v: { id: 94 },
  mp4v: { id: 95 },
  mov: { id: 96 },
  swf: { id: 97 },
  wmv: { id: 98 },
  rm: { id: 99 },
  ogv: { id: 100 },
  indd: { id: 101 },
  indt: { id: 102 },
  incx: { id: 103 },
  wwcx: { id: 104 },
  doc: { id: 105 },
  docx: { id: 106 },
  dot: { id: 107 },
  dotx: { id: 108 },
  mdb: { id: 109 },
  mpp: { id: 110 },
  ics: { id: 111 },
  xls: { id: 112 },
  xlsx: { id: 113 },
  xlk: { id: 114 },
  xlsm: { id: 115 },
  xlt: { id: 116 },
  xltm: { id: 117 },
  csv: { id: 118 },
  tsv: { id: 119 },
  tab: { id: 120 },
  pps: { id: 121 },
  ppsx: { id: 122 },
  ppt: { id: 123 },
  pptx: { id: 124 },
  pot: { id: 125 },
  thmx: { id: 126 },
  pdf: { id: 127 },
  ps: { id: 128 },
  qxd: { id: 129 },
  rtf: { id: 130 },
  sxc: { id: 131 },
  sxi: { id: 132 },
  sxw: { id: 133 },
  odt: { id: 134 },
  ods: { id: 135 },
  ots: { id: 136 },
  odp: { id: 137 },
  otp: { id: 138 },
  epub: { id: 139 },
  dvi: { id: 140 },
  key: { id: 141 },
  keynote: { id: 142 },
  pez: { id: 143 },
  aac: { id: 144 },
  m4a: { id: 145 },
  au: { id: 146 },
  aif: { id: 147 },
  aiff: { id: 148 },
  aifc: { id: 149 },
  mp3: { id: 150 },
  wav: { id: 151 },
  wma: { id: 152 },
  midi: { id: 153 },
  oga: { id: 154 },
  ogg: { id: 155 },
  ra: { id: 156 },
  vox: { id: 157 },
  voc: { id: 158 },
  "7z": { id: 159 },
  arj: { id: 160 },
  bz2: { id: 161 },
  cab: { id: 162 },
  gz: { id: 163 },
  gzip: { id: 164 },
  iso: { id: 165 },
  lha: { id: 166 },
  sit: { id: 167 },
  tgz: { id: 168 },
  jar: { id: 169 },
  rar: { id: 170 },
  tar: { id: 171 },
  zip: { id: 172 },
  gpg: { id: 173 },
  htm: { id: 174 },
  html: { id: 175 },
  xhtml: { id: 176 },
  xht: { id: 177 },
  css: { id: 178 },
  less: { id: 179 },
  sass: { id: 180 },
  js: { id: 181 },
  json: { id: 182 },
  atom: { id: 183 },
  rss: { id: 184 },
  xml: { id: 185 },
  xsl: { id: 186 },
  xslt: { id: 187 },
  md: { id: 188 },
  markdown: { id: 189 },
  as: { id: 190 },
  fla: { id: 191 },
  eml: { id: 192 },
  text: { id: 193 },
  txt: { id: 194 },
  freeformblock: { id: 195 },
  textblock: { id: 196 },
  htmlblock: { id: 197 },
  textplusimageblock: { id: 198 },
  imageblock: { id: 199 },
  abtestblock: { id: 200 },
  dynamicblock: { id: 201 },
  stylingblock: { id: 202 },
  einsteincontentblock: { id: 203 },
  webpage: { id: 205 },
  webtemplate: { id: 206 },
  templatebasedemail: { id: 207 },
  htmlemail: { id: 208 },
  textonlyemail: { id: 209 },
  socialshareblock: { id: 210 },
  socialfollowblock: { id: 211 },
  buttonblock: { id: 212 },
  layoutblock: { id: 213 },
  defaulttemplate: { id: 214 },
  smartcaptureblock: { id: 215 },
  smartcaptureformfieldblock: { id: 216 },
  smartcapturesubmitoptionsblock: { id: 217 },
  slotpropertiesblock: { id: 218 },
  externalcontentblock: { id: 219 },
  codesnippetblock: { id: 220 },
  rssfeedblock: { id: 221 },
  formstylingblock: { id: 222 },
  referenceblock: { id: 223 },
  imagecarouselblock: { id: 224 },
  customblock: { id: 225 },
  liveimageblock: { id: 226 },
  livesettingblock: { id: 227 },
  contentmap: { id: 228 },
  jsonmessage: { id: 230 },
  icemailformblock: { id: 232 },
};
export const HTTPS_CODES: any = {
  success: 200,
  failure: 500,
  authorized: 401,
  badRequest: 400,
};
export const SFMC_URLS: any = {
  auth: `https://${process.env.sfmc_subdomain}.auth.marketingcloudapis.com/v2/token`,
  tags: "/hub/v1/objects/media/tags/",
  assets: "/asset/v1/content/assets",
  base: `https://${process.env.sfmc_subdomain}.rest.marketingcloudapis.com`,
};
export const AUTH_URLS: any = {
  local1: "https://local.dev:4200",
  local2: "http://localhost:4200",
};
export const SLACK_URLS: any = {
  postMessage: "https://slack.com/api/chat.postMessage",
  update: "https://slack.com/api/chat.update",
  getUser: "https://slack.com/api/users.info?user=",
};
export const SLACK_ACTION_TYPES: any = {
  addToSFMC: "AddToSFMC",
  noToSFMC: "NoToSFMC",
};
export const OPENAPI_URLS: any = {
  imageGeneration: "https://api.openai.com/v1/images/generations",
};
export const ENV: any = {
  incomingTable: process.env.incomingTable || "",
  outgoingTable: process.env.outgoingTable || "",
  dalleHistory: process.env.dalleHistory || "",
  settings: process.env.settings || "",
  openAPIKey: process.env.openAPIKey || "",
  content: process.env.content || "",
  sfmc_client_id: process.env.sfmc_client_id || "",
  sfmc_client_secret: process.env.sfmc_client_secret || "",
  sfmc_mid: process.env.sfmc_mid || "",
  sfmc_subdomain: process.env.sfmc_subdomain || "",
  sfmc_category_id: process.env.sfmc_category_id || "",
  sfmc_authorized_apps: process.env.sfmc_authorized_apps || "",
  azure_key: process.env.azure_key || "",
  sarah_id: process.env.sarah_id || "",
  sarah_token: process.env.sarah_token || "",
  azure_domain: process.env.azure_domain || "",
  contentURL: `https://s3.amazonaws.com/${process.env.content}/image-store/`,
  azure: `https://${process.env.azure_domain}.cognitiveservices.azure.com/vision/v3.2/analyze?visualFeatures=Categories,Color,Objects`,
  sarah_app_id: process.env.sarah_app_id || "",
  sarah_authorized_teams: process.env.sarah_authorized_teams || "",
  default_image_size: process.env.default_image_size || "512x512",
  default_app_id: process.env.default_app_id || "SARAH-APP",
};
